"""Initial SQLModel schema with all tables

Revision ID: e4bcef60731d
Revises: 
Create Date: 2025-12-12 20:25:16.911055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4bcef60731d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create trigger function for updating updated_at timestamp
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ language 'plpgsql';
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_metrics',
    sa.Column('metric_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=15, scale=4), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_metrics_name', 'system_metrics', ['metric_name'], unique=False)
    op.create_index('idx_system_metrics_tags', 'system_metrics', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_system_metrics_timestamp', 'system_metrics', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('key_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('last_request_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('idx_api_keys_active', 'api_keys', ['is_active'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('idx_api_keys_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_path', sa.Text(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('subreddits', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('competitor_keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('polling_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('fetch_limit_per_subreddit', sa.Integer(), nullable=False),
    sa.Column('historical_days', sa.Integer(), nullable=False),
    sa.Column('enable_sentiment', sa.Boolean(), nullable=False),
    sa.Column('enable_intent', sa.Boolean(), nullable=False),
    sa.Column('enable_pain_detection', sa.Boolean(), nullable=False),
    sa.Column('enable_entity_extraction', sa.Boolean(), nullable=False),
    sa.Column('enable_topic_extraction', sa.Boolean(), nullable=False),
    sa.Column('enable_embedding', sa.Boolean(), nullable=False),
    sa.Column('crisis_threshold_multiplier', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('trend_growth_threshold', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_fetch_at', sa.DateTime(), nullable=True),
    sa.Column('total_posts_fetched', sa.Integer(), nullable=False),
    sa.Column('total_posts_analyzed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profiles_active', 'profiles', ['is_active'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('idx_profiles_user_id', 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_email', sa.Boolean(), nullable=False),
    sa.Column('notification_in_app', sa.Boolean(), nullable=False),
    sa.Column('notification_crisis_alerts', sa.Boolean(), nullable=False),
    sa.Column('notification_daily_summary', sa.Boolean(), nullable=False),
    sa.Column('notification_trending_topics', sa.Boolean(), nullable=False),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('competitor_analysis',
    sa.Column('competitor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('competitor_keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('sentiment_positive', sa.Integer(), nullable=False),
    sa.Column('sentiment_neutral', sa.Integer(), nullable=False),
    sa.Column('sentiment_negative', sa.Integer(), nullable=False),
    sa.Column('average_sentiment_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('average_engagement', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('pain_point_count', sa.Integer(), nullable=False),
    sa.Column('top_pain_points', sa.JSON(), nullable=True),
    sa.Column('top_topics', sa.JSON(), nullable=True),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('sample_post_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_competitor_analysis_competitor', 'competitor_analysis', ['competitor_name'], unique=False)
    op.create_index('idx_competitor_analysis_date', 'competitor_analysis', ['analysis_date'], unique=False)
    op.create_index('idx_competitor_analysis_profile_id', 'competitor_analysis', ['profile_id'], unique=False)
    op.create_index(op.f('ix_competitor_analysis_profile_id'), 'competitor_analysis', ['profile_id'], unique=False)
    op.create_table('crisis_alerts',
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('negative_count_current', sa.Integer(), nullable=True),
    sa.Column('negative_count_baseline', sa.Integer(), nullable=True),
    sa.Column('spike_multiplier', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('affected_posts_count', sa.Integer(), nullable=True),
    sa.Column('detection_window_start', sa.DateTime(), nullable=False),
    sa.Column('detection_window_end', sa.DateTime(), nullable=False),
    sa.Column('baseline_window_start', sa.DateTime(), nullable=True),
    sa.Column('baseline_window_end', sa.DateTime(), nullable=True),
    sa.Column('sample_post_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('top_pain_points', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('top_keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('notification_channels', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crisis_alerts_created_at', 'crisis_alerts', ['created_at'], unique=False)
    op.create_index('idx_crisis_alerts_profile_id', 'crisis_alerts', ['profile_id'], unique=False)
    op.create_index('idx_crisis_alerts_severity', 'crisis_alerts', ['severity'], unique=False)
    op.create_index('idx_crisis_alerts_status', 'crisis_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_crisis_alerts_profile_id'), 'crisis_alerts', ['profile_id'], unique=False)
    op.create_table('customer_language',
    sa.Column('phrase', sa.Text(), nullable=True),
    sa.Column('phrase_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('sentiment_association', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('average_sentiment_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('common_topics', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sample_contexts', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('tf_idf_score', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('importance_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_language_date', 'customer_language', ['analysis_date'], unique=False)
    op.create_index('idx_customer_language_occurrence', 'customer_language', ['occurrence_count'], unique=False)
    op.create_index('idx_customer_language_phrase', 'customer_language', ['phrase'], unique=False)
    op.create_index('idx_customer_language_profile_id', 'customer_language', ['profile_id'], unique=False)
    op.create_index(op.f('ix_customer_language_profile_id'), 'customer_language', ['profile_id'], unique=False)
    op.create_table('influencers',
    sa.Column('reddit_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('total_activity', sa.Integer(), nullable=False),
    sa.Column('total_karma', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('total_comments_received', sa.Integer(), nullable=False),
    sa.Column('average_comments', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('positive_posts', sa.Integer(), nullable=False),
    sa.Column('neutral_posts', sa.Integer(), nullable=False),
    sa.Column('negative_posts', sa.Integer(), nullable=False),
    sa.Column('sentiment_ratio', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('influence_score', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('influence_rank', sa.Integer(), nullable=True),
    sa.Column('top_topics', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('top_subreddits', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('sample_post_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_influencers_date', 'influencers', ['analysis_date'], unique=False)
    op.create_index('idx_influencers_profile_id', 'influencers', ['profile_id'], unique=False)
    op.create_index('idx_influencers_score', 'influencers', ['influence_score'], unique=False)
    op.create_index('idx_influencers_username', 'influencers', ['reddit_username'], unique=False)
    op.create_index(op.f('ix_influencers_profile_id'), 'influencers', ['profile_id'], unique=False)
    op.create_table('notifications',
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('related_entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('channels', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sent_via_email', sa.Boolean(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notifications_is_read', 'notifications', ['is_read'], unique=False, postgresql_where=sa.text('is_read = FALSE'))
    op.create_index('idx_notifications_profile_id', 'notifications', ['profile_id'], unique=False)
    op.create_index('idx_notifications_type', 'notifications', ['type'], unique=False)
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_profile_id'), 'notifications', ['profile_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('reddit_posts',
    sa.Column('reddit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subreddit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('selftext', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('upvote_ratio', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matched_keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reddit_posts_created_utc', 'reddit_posts', ['created_utc'], unique=False)
    op.create_index('idx_reddit_posts_profile_id', 'reddit_posts', ['profile_id'], unique=False)
    op.create_index('idx_reddit_posts_reddit_id', 'reddit_posts', ['reddit_id'], unique=False)
    op.create_index('idx_reddit_posts_status', 'reddit_posts', ['processing_status'], unique=False)
    op.create_index('idx_reddit_posts_subreddit', 'reddit_posts', ['subreddit'], unique=False)
    op.create_index('idx_reddit_posts_user_id', 'reddit_posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_reddit_posts_profile_id'), 'reddit_posts', ['profile_id'], unique=False)
    op.create_index(op.f('ix_reddit_posts_reddit_id'), 'reddit_posts', ['reddit_id'], unique=True)
    op.create_index(op.f('ix_reddit_posts_subreddit'), 'reddit_posts', ['subreddit'], unique=False)
    op.create_index(op.f('ix_reddit_posts_user_id'), 'reddit_posts', ['user_id'], unique=False)
    op.create_table('search_history',
    sa.Column('search_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('query_vector', sa.JSON(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('clicked_post_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('search_duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_history_created_at', 'search_history', ['created_at'], unique=False)
    op.create_index('idx_search_history_profile_id', 'search_history', ['profile_id'], unique=False)
    op.create_index('idx_search_history_user_id', 'search_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_search_history_profile_id'), 'search_history', ['profile_id'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('summary_reports',
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_posts', sa.Integer(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('total_engagement', sa.Integer(), nullable=False),
    sa.Column('sentiment_positive', sa.Integer(), nullable=False),
    sa.Column('sentiment_neutral', sa.Integer(), nullable=False),
    sa.Column('sentiment_negative', sa.Integer(), nullable=False),
    sa.Column('sentiment_trend', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('top_topics', sa.JSON(), nullable=True),
    sa.Column('top_pain_points', sa.JSON(), nullable=True),
    sa.Column('top_subreddits', sa.JSON(), nullable=True),
    sa.Column('top_keywords', sa.JSON(), nullable=True),
    sa.Column('crisis_alerts_count', sa.Integer(), nullable=False),
    sa.Column('trends_count', sa.Integer(), nullable=False),
    sa.Column('change_vs_previous_period', sa.JSON(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_channels', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_summary_reports_date', 'summary_reports', ['report_date'], unique=False)
    op.create_index('idx_summary_reports_profile_id', 'summary_reports', ['profile_id'], unique=False)
    op.create_index('idx_summary_reports_type', 'summary_reports', ['report_type'], unique=False)
    op.create_index('idx_summary_reports_user_id', 'summary_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_summary_reports_profile_id'), 'summary_reports', ['profile_id'], unique=False)
    op.create_index(op.f('ix_summary_reports_user_id'), 'summary_reports', ['user_id'], unique=False)
    op.create_table('trends',
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trend_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('previous_count', sa.Integer(), nullable=False),
    sa.Column('growth_rate', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('growth_absolute', sa.Integer(), nullable=True),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('comparison_period_start', sa.DateTime(), nullable=False),
    sa.Column('comparison_period_end', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trends_created_at', 'trends', ['created_at'], unique=False)
    op.create_index('idx_trends_growth_rate', 'trends', ['growth_rate'], unique=False)
    op.create_index('idx_trends_profile_id', 'trends', ['profile_id'], unique=False)
    op.create_index('idx_trends_status', 'trends', ['status'], unique=False)
    op.create_index(op.f('ix_trends_profile_id'), 'trends', ['profile_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('secret_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('events', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhooks_active', 'webhooks', ['is_active'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('idx_webhooks_profile_id', 'webhooks', ['profile_id'], unique=False)
    op.create_index('idx_webhooks_user_id', 'webhooks', ['user_id'], unique=False)
    op.create_index(op.f('ix_webhooks_profile_id'), 'webhooks', ['profile_id'], unique=False)
    op.create_index(op.f('ix_webhooks_user_id'), 'webhooks', ['user_id'], unique=False)
    op.create_table('ai_analysis',
    sa.Column('sentiment_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sentiment_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('emotion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emotion_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('intent_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intent_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('has_pain_point', sa.Boolean(), nullable=False),
    sa.Column('pain_point_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pain_point_severity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pain_point_phrases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('topics', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('topic_scores', sa.ARRAY(sa.DECIMAL(precision=5, scale=4)), nullable=True),
    sa.Column('main_topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('keyword_scores', sa.ARRAY(sa.DECIMAL(precision=5, scale=4)), nullable=True),
    sa.Column('embedding_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding_generated', sa.Boolean(), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['reddit_posts.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_analysis_intent', 'ai_analysis', ['intent_label'], unique=False)
    op.create_index('idx_ai_analysis_pain_point', 'ai_analysis', ['has_pain_point'], unique=False, postgresql_where=sa.text('has_pain_point = TRUE'))
    op.create_index('idx_ai_analysis_post_id', 'ai_analysis', ['post_id'], unique=False)
    op.create_index('idx_ai_analysis_profile_id', 'ai_analysis', ['profile_id'], unique=False)
    op.create_index('idx_ai_analysis_sentiment', 'ai_analysis', ['sentiment_label'], unique=False)
    op.create_index('idx_ai_analysis_topics', 'ai_analysis', ['topics'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_ai_analysis_post_id'), 'ai_analysis', ['post_id'], unique=True)
    op.create_index(op.f('ix_ai_analysis_profile_id'), 'ai_analysis', ['profile_id'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_attempt', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_logs_created_at', 'webhook_logs', ['created_at'], unique=False)
    op.create_index('idx_webhook_logs_success', 'webhook_logs', ['success'], unique=False)
    op.create_index('idx_webhook_logs_webhook_id', 'webhook_logs', ['webhook_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_webhook_id'), 'webhook_logs', ['webhook_id'], unique=False)

    # Create triggers for automatic updated_at timestamp updates
    tables_with_updated_at = [
        'users', 'api_keys', 'profiles', 'user_preferences', 'competitor_analysis',
        'crisis_alerts', 'customer_language', 'influencers', 'notifications',
        'reddit_posts', 'summary_reports', 'trends', 'webhooks', 'ai_analysis'
    ]

    for table in tables_with_updated_at:
        op.execute(f"""
            CREATE TRIGGER update_{table}_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
        """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop triggers for updated_at timestamp updates
    tables_with_updated_at = [
        'users', 'api_keys', 'profiles', 'user_preferences', 'competitor_analysis',
        'crisis_alerts', 'customer_language', 'influencers', 'notifications',
        'reddit_posts', 'summary_reports', 'trends', 'webhooks', 'ai_analysis'
    ]

    for table in tables_with_updated_at:
        op.execute(f"DROP TRIGGER IF EXISTS update_{table}_updated_at ON {table};")

    # Drop trigger function
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_logs_webhook_id'), table_name='webhook_logs')
    op.drop_index('idx_webhook_logs_webhook_id', table_name='webhook_logs')
    op.drop_index('idx_webhook_logs_success', table_name='webhook_logs')
    op.drop_index('idx_webhook_logs_created_at', table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_ai_analysis_profile_id'), table_name='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_post_id'), table_name='ai_analysis')
    op.drop_index('idx_ai_analysis_topics', table_name='ai_analysis', postgresql_using='gin')
    op.drop_index('idx_ai_analysis_sentiment', table_name='ai_analysis')
    op.drop_index('idx_ai_analysis_profile_id', table_name='ai_analysis')
    op.drop_index('idx_ai_analysis_post_id', table_name='ai_analysis')
    op.drop_index('idx_ai_analysis_pain_point', table_name='ai_analysis', postgresql_where=sa.text('has_pain_point = TRUE'))
    op.drop_index('idx_ai_analysis_intent', table_name='ai_analysis')
    op.drop_table('ai_analysis')
    op.drop_index(op.f('ix_webhooks_user_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_profile_id'), table_name='webhooks')
    op.drop_index('idx_webhooks_user_id', table_name='webhooks')
    op.drop_index('idx_webhooks_profile_id', table_name='webhooks')
    op.drop_index('idx_webhooks_active', table_name='webhooks', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_trends_profile_id'), table_name='trends')
    op.drop_index('idx_trends_status', table_name='trends')
    op.drop_index('idx_trends_profile_id', table_name='trends')
    op.drop_index('idx_trends_growth_rate', table_name='trends')
    op.drop_index('idx_trends_created_at', table_name='trends')
    op.drop_table('trends')
    op.drop_index(op.f('ix_summary_reports_user_id'), table_name='summary_reports')
    op.drop_index(op.f('ix_summary_reports_profile_id'), table_name='summary_reports')
    op.drop_index('idx_summary_reports_user_id', table_name='summary_reports')
    op.drop_index('idx_summary_reports_type', table_name='summary_reports')
    op.drop_index('idx_summary_reports_profile_id', table_name='summary_reports')
    op.drop_index('idx_summary_reports_date', table_name='summary_reports')
    op.drop_table('summary_reports')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_profile_id'), table_name='search_history')
    op.drop_index('idx_search_history_user_id', table_name='search_history')
    op.drop_index('idx_search_history_profile_id', table_name='search_history')
    op.drop_index('idx_search_history_created_at', table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_reddit_posts_user_id'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_subreddit'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_reddit_id'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_profile_id'), table_name='reddit_posts')
    op.drop_index('idx_reddit_posts_user_id', table_name='reddit_posts')
    op.drop_index('idx_reddit_posts_subreddit', table_name='reddit_posts')
    op.drop_index('idx_reddit_posts_status', table_name='reddit_posts')
    op.drop_index('idx_reddit_posts_reddit_id', table_name='reddit_posts')
    op.drop_index('idx_reddit_posts_profile_id', table_name='reddit_posts')
    op.drop_index('idx_reddit_posts_created_utc', table_name='reddit_posts')
    op.drop_table('reddit_posts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_profile_id'), table_name='notifications')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_index('idx_notifications_type', table_name='notifications')
    op.drop_index('idx_notifications_profile_id', table_name='notifications')
    op.drop_index('idx_notifications_is_read', table_name='notifications', postgresql_where=sa.text('is_read = FALSE'))
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_influencers_profile_id'), table_name='influencers')
    op.drop_index('idx_influencers_username', table_name='influencers')
    op.drop_index('idx_influencers_score', table_name='influencers')
    op.drop_index('idx_influencers_profile_id', table_name='influencers')
    op.drop_index('idx_influencers_date', table_name='influencers')
    op.drop_table('influencers')
    op.drop_index(op.f('ix_customer_language_profile_id'), table_name='customer_language')
    op.drop_index('idx_customer_language_profile_id', table_name='customer_language')
    op.drop_index('idx_customer_language_phrase', table_name='customer_language')
    op.drop_index('idx_customer_language_occurrence', table_name='customer_language')
    op.drop_index('idx_customer_language_date', table_name='customer_language')
    op.drop_table('customer_language')
    op.drop_index(op.f('ix_crisis_alerts_profile_id'), table_name='crisis_alerts')
    op.drop_index('idx_crisis_alerts_status', table_name='crisis_alerts')
    op.drop_index('idx_crisis_alerts_severity', table_name='crisis_alerts')
    op.drop_index('idx_crisis_alerts_profile_id', table_name='crisis_alerts')
    op.drop_index('idx_crisis_alerts_created_at', table_name='crisis_alerts')
    op.drop_table('crisis_alerts')
    op.drop_index(op.f('ix_competitor_analysis_profile_id'), table_name='competitor_analysis')
    op.drop_index('idx_competitor_analysis_profile_id', table_name='competitor_analysis')
    op.drop_index('idx_competitor_analysis_date', table_name='competitor_analysis')
    op.drop_index('idx_competitor_analysis_competitor', table_name='competitor_analysis')
    op.drop_table('competitor_analysis')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index('idx_profiles_user_id', table_name='profiles')
    op.drop_index('idx_profiles_active', table_name='profiles', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('profiles')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index('idx_api_keys_user_id', table_name='api_keys')
    op.drop_index('idx_api_keys_hash', table_name='api_keys')
    op.drop_index('idx_api_keys_active', table_name='api_keys', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_system_metrics_timestamp', table_name='system_metrics')
    op.drop_index('idx_system_metrics_tags', table_name='system_metrics', postgresql_using='gin')
    op.drop_index('idx_system_metrics_name', table_name='system_metrics')
    op.drop_table('system_metrics')
    # ### end Alembic commands ###
